CREATE DATABASE Dopameme;
\c my_database

CREATE TABLE "Follow" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp
);

CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" varchar(16) UNIQUE NOT NULL,
  "password_hash" char(64) NOT NULL,
  "nickname" varchar(16) UNIQUE NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "Video" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "title" varchar(100) NOT NULL,
  "video_url" varchar(256) NOT NULL,
  "thumbnail_url" varchar(256) NOT NULL,
  "is_crawl" boolean NOT NULL,
  "published_at" timestamp
);

CREATE TABLE "Notification" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "video_id" integer,
  "is_read" boolean NOT NULL,
  "created_at" timestamp
);

ALTER TABLE "Video" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Follow" ADD FOREIGN KEY ("followed_user_id") REFERENCES "User" ("id");

ALTER TABLE "Follow" ADD FOREIGN KEY ("following_user_id") REFERENCES "User" ("id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("video_id") REFERENCES "Video" ("id");
